rabbitmq:
  #  address: 127.0.0.1/5657
  host: 127.0.0.1
  port: 8090
  username: guest
  password: guest
  pubisher-confirms: true #消息发送到交换机确认机制，是否确认回调
  publisher-returns: true #消息发送到交换机确认机制，是否返回回调
  listener:
    simple:
      acknowledge-model: manual #采用手动应答
      concurrency: 1 #指定最小的消费者数量
      max-concurrency: 3 #指定最大的消费者数量
      retry:
        enabled: true #是否支持重试