server:
  port: 8080
  servlet:
    session:
      timeout: 36000
  max-http-header-size: "102400"

#rootPath:

spring:
  main:
    lazy-initialization: true

  health:
    redis:
      enabled: false
  rabbitmq:
    #  address: 127.0.0.1/5657
    host: localhost
    port: 5672
    username: guest
    password: guest
    pubisher-confirms: true #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true #消息发送到交换机确认机制，是否返回回调
    listener:
      simple:
        acknowledge-model: manual #采用手动应答
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 3 #指定最大的消费者数量
        retry:
          enabled: true #是否支持重试

  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    prefix: classpath:/view/
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB #单个文件最大大小
      max-request-size: 2048MB #上传数据总大小
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: cims123$%
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      #log4j
      filters: #stat,log4j
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000;druid.stat.logSlowSql=true
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: admin
        login-password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 3
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 300
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    lettuce:
      shutdown-timeout: 5000
    timeout: 5000

mybatis-plus:
  mapper-locations: classpath*:/mapper_xml/*.xml
  type-aliases-package: com.demo.springboot.*
  global-config:
    db-config:
      field-strategy: ignored
      # 主键策略·
      id-type: AUTO
    #      logic-delete-value: 1
    #      logic-not-delete-value: 0
    # 是否显示myBatis图标
    banner: false







